### ISSUE TITLE
Add support for AdoptOpenJDK builds of OpenJDK

### ISSUE THREAD

**Issue by ignatovich-artem** [lean-delivery/ansible-role-java#76]
##### SUMMARY

Add support for AdoptOpenJDK builds of OpenJDK
##### ISSUE TYPE
 - Feature Idea

**Comment by perlun** [comment]
Since a while back, AdoptOpenJDK provides `.deb` and `.rpm` packages of their builds: https://adoptopenjdk.net/installation.html#linux-pkg

Are there any plans to support these in this Ansible role? It would be really nice, since it's typically the preferred way to deploy AdoptOpenJDK when possible.

**Comment by pavelpikta** [comment]
Hi @perlun,  yes, we support AdopOpenJDK installation from repositories. See example in [molecule scenarios ](https://github.com/lean-delivery/ansible-role-java/blob/master/molecule/cloud-aws-adoptopenjdk-12/molecule.yml)

**Comment by perlun** [comment]
Wonderful, thanks! :+1:
